### ISSUE TITLE
Type 'Database' is not assignable to type 'Extension'

### ISSUE THREAD

**Issue by martin-cycle** [ueberdosis/hocuspocus#555] opened 2023-03-29 14:09 UTC
**Description**
I have typing problems with my configuration and the extensions I'm using. This error occurs for the Database and the Logger extensions. I am using ncc to build my node app, this could be linked to it but I'm not sure. I managed to make it work by casting the extensions used `as unknown as Extension`.

**Expected behavior**
The project should build without casting the extensions or there should be some more information about required versions of packages to use.

**Screenshot, video, or GIF**

![Screenshot 2023-03-29 at 16 05 49](https://user-images.githubusercontent.com/66952775/228564145-a3c675be-5101-4a22-b2f7-cd733c4448ba.png)

**Environment?**
 - operating system: docker node 16 on MacOS 
 - Hocuspocus version: 1.1.3
 - Typescript:  "target": "es2019"

**Comment by janthurau** [comment] 2023-03-30 07:57
hey @martin-cycle, just to check, this also looks related to different versions (see #549). Did you resolve this?

**Comment by martin-cycle** [comment] 2023-03-30 10:25
The #549 was solved by simply calling my winston logger a bit differently but here I am still facing the issue. I'm gonna try to upgrade the hocuspocus to V2 to see if I still have the problem.

**Comment by janthurau** [comment] 2023-04-10 18:24
Let me know if you still have that issue, until then, closed as I cant reproduce this.

**Closed** 2023-04-10 18:24 UTC
Labels: bug

**Comment by carsonbird** [comment] 2024-03-11 05:43
I'm seeing the same issue here.
