### ISSUE TITLE
WebsocketProvider not destroyed

### ISSUE THREAD

**Issue by lin52025iq** [ueberdosis/hocuspocus#636] opened 2023-06-20 07:54 UTC
**Description**
HocuspocusProviderWebsocket is not destroyed when HocuspocusProvider's destroy is called.

**Steps to reproduce the bug**
```js
// init provider
const socket = new HocuspocusProviderWebsocket({
  url: 'ws://127.0.0.1:1234',
})

const provider = new HocuspocusProvider({
  websocketProvider: socket,
  name: 'hocuspocus-demo',
  broadcast: false,
})

// do
provider.destory()

// result: the status of websocket alreadly is pending,
```

**Expected behavior**
HocuspocusProviderWebsocket is destroyed

**Screenshot, video, or GIF**

**Environment?**
 - operating system: all
 - browser: yes
 - mobile/desktop: all
 - Hocuspocus version: 2.1.0

**Additional context**

**Comment by georeith** [comment] 2023-06-20 07:57
+1 I've been meaning to make a ticket about this, I'm manually destroying the websocket provider at the same time in our application.

**Comment by janthurau** [comment] 2023-06-21 18:27
hmm yep we're still lacking documentation for this unfortunately. It's intended behavior as the socket can be created without a document connected/connecting.

If you want to close the connection, you need to destroy the websocket provider as well (`socket.disconnect()`). Documentation is in the process ..

**Comment by romansp** [comment] 2023-06-28 23:30
I agree with the intended behavior described above but I noticed something else that seems unexpected.

I'm reusing single `HocuspocusProviderWebsocket` across multiple `HocuspocusProvider` instances and then manually destroy these when required (`onBeforeUnmount` hook in Vue). But it seems that provider doesn't unsubscribe properly from `websocketProvider` which leads to a memory leak.

For example, `onStatus` hook will still be called for websocket reconnect events later even after `HocuspocusProvider` has been explicitly destroyed.
 
Here handler is configured, but `this.removeAllListeners()` in destroy call won't unsubscribe this.
https://github.com/ueberdosis/hocuspocus/blob/6ca39f2b5768ea1abadd1c88265f5b85d564a3d4/packages/provider/src/HocuspocusProvider.ts#L180

Will try to provide a minimal repro soon.

**Comment by janthurau** [comment] 2023-07-14 18:50
Closing this, as the behaviour is intended. The memory leak has already been fixed by @raineorshine :)

**Closed by janthurau** 2023-07-14 18:50 UTC
Labels: bug
